// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"shikakaQuelor/bootleg/internals/systembolaget"
	"shikakaQuelor/bootleg/internals/taxes"
	"shikakaQuelor/bootleg/views/components"
)

func Index(productData []taxes.Product, metadata systembolaget.Metadata) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><script src=\"https://unpkg.com/htmx.org@2.0.2\" integrity=\"sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ\" crossorigin=\"anonymous\"></script><script src=\"https://unpkg.com/hyperscript.org@0.9.12\"></script><script src=\"https://unpkg.com/htmx.org@1.9.12/dist/ext/json-enc.js\"></script><link href=\"/static/style.css\" rel=\"stylesheet\"><title>Bootleg</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"></head><div class=\"w-screen h-max min-h-svh\"><div id=\"bg\" class=\"background-svg fixed h-full -z-50\"></div><div class=\"flex flex-col justify-center py-3 h-full\"><h1 class=\"text-6xl font-bold mx-auto text-center text-transparent text-stroke-2 font-mono \">Bootleg</h1><div class=\"flex-initial sticky top-0 z-10\"><div class=\"max-w-full my-1 mx-2 md:max-w-lg md:mx-auto\"><form><input name=\"search\" hx-post=\"/search\" hx-trigger=\"search, submit\" hx-target=\"#search-results\" hx-swap=\"innerHTML\" class=\"bg-light-green border border-gold-yellow text-white text-3xl rounded-lg focus:ring-gold-yellow focus:border-gold-yellow block w-full ps-10 p-2.5\" type=\"search\" placeholder=\"Sök här efter alkodryck\"></form></div></div><div id=\"search-results\" class=\"mx-4 gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Products(productData, metadata).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
