// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"shikakaQuelor/bootleg/internals/systembolaget"
	"shikakaQuelor/bootleg/internals/taxes"
	"shikakaQuelor/bootleg/views/components"
)

func Index(productData []taxes.Product, metadata systembolaget.Metadata) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><script src=\"https://unpkg.com/htmx.org@2.0.1\" integrity=\"sha384-QWGpdj554B4ETpJJC9z+ZHJcA/i59TyjxEPXiiUgN2WmTyV5OEZWCD6gQhgkdpB/\" crossorigin=\"anonymous\"></script><script>{htmx.logAll()}</script><link href=\"/static/style.css\" rel=\"stylesheet\"><title>Spritmonopolet</title></head><div class=\"flex flex-col justify-center min-h-svh\"><div class=\"flex-initial\"><h1 class=\"text-6xl font-bold mx-auto text-center mb-2\">Bootleg</h1><div class=\"max-w-lg mx-auto\"><input name=\"search\" hx-post=\"/search\" hx-trigger=\"search\" hx-target=\"#search-results\" hx-swap=\"innerHTML\" class=\"bg-light-green border border-gold-yellow text-gray-900 text-sm rounded-lg focus:ring-gold-yellow focus:border-gold-yellow block w-full ps-10 p-2.5  dark:bg-light-green dark:border-gold-yellow dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500\" type=\"search\" placeholder=\"Sök här efter alkodryck\"></div><div class=\"text-center\"><p>Sök efter en alkodryck i Systembolagets sortiment för att se hur stor andel av priset som är skatt</p></div></div><div id=\"search-results\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Products(productData, metadata).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
